export const semiFinalists = [
  {
    teamName: "Overleap",
    teamLink: "https://dorahacks.io/buidl/13092",
    teamMVP: "https://t.me/overleap_bot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "MoneyTab",
    teamLink: "https://dorahacks.io/buidl/13658",
    teamMVP: "https://t.me/MoneyTabBot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "FansNetwork",
    teamLink: "https://dorahacks.io/buidl/13610",
    teamMVP: "https://t.me/tinaaaaalee_gf_bot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Dayton",
    teamLink: "https://dorahacks.io/buidl/13603",
    teamMVP: "https://t.me/DaytonAppBot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Checkiton",
    teamLink: "https://dorahacks.io/buidl/13561",
    teamMVP: "https://t.me/checkitonbot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "SuperFunSocial",
    teamLink: "https://dorahacks.io/buidl/13246",
    teamMVP: "https://t.me/SuperFunSocial_bot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "EQYTY",
    teamLink: "https://dorahacks.io/buidl/11648",
    teamMVP: "https://t.me/eqytybot",
    teamTrack: "eCommerce",
  },
  {
    teamName: "AI HUB",
    teamLink: "https://dorahacks.io/buidl/11538",
    teamMVP: "https://t.me/ai_hub_ton_bot",
    teamTrack: "eCommerce",
  },
  {
    teamName: "Common Course",
    teamLink: "https://dorahacks.io/buidl/11476",
    teamMVP: "https://t.me/CoCourseBot",
    teamTrack: "eCommerce",
  },
  {
    teamName: "InOne",
    teamLink: "https://dorahacks.io/buidl/11369",
    teamMVP: "https://t.me/inone_beta_bot",
    teamTrack: "eCommerce",
  },
  {
    teamName: "SchoolTon",
    teamLink: "https://dorahacks.io/buidl/13643",
    teamMVP: "https://t.me/schoolton_bot/quizapp",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Openteller ATM",
    teamLink: "https://dorahacks.io/buidl/13002",
    teamMVP: "https://t.me/OpentellerBot",
    teamTrack: "eCommerce",
  },
  {
    teamName: "Telegram built-in e-Shop Window",
    teamLink: "https://dorahacks.io/buidl/12854",
    teamMVP: "https://t.me/ShopigramBot",
    teamTrack: "eCommerce",
  },
  {
    teamName: "Freema",
    teamLink: "https://dorahacks.io/buidl/11904",
    teamMVP: "https://t.me/freema_for_buyers_bot",
    teamTrack: "eCommerce",
  },
  {
    teamName: "TON Game Center",
    teamLink: "https://dorahacks.io/buidl/11861",
    teamMVP: "https://t.me/tongamecenter_bot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "TON Map",
    teamLink: "https://dorahacks.io/buidl/11685",
    teamMVP: "https://t.me/TheTonMapBot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Swipy",
    teamLink: "https://dorahacks.io/buidl/11601",
    teamMVP: "https://t.me/SwipyDatingBot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Tonalytics",
    teamLink: "https://dorahacks.io/buidl/11614",
    teamMVP: "https://t.me/tonalytics_bot/app",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Go Do Chain",
    teamLink: "https://dorahacks.io/buidl/11762",
    teamMVP: "https://t.me/godochain_bot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Achivator: Telegram social engagement platform",
    teamLink: "https://dorahacks.io/buidl/11574",
    teamMVP: "https://t.me/achivator_bot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Umnicoins - Educational currency TON",
    teamLink: "https://dorahacks.io/buidl/11748",
    teamMVP: "https://t.me/umnicoins_bot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Palim Palim",
    teamLink: "https://dorahacks.io/buidl/11773",
    teamMVP: "https://t.me/DEC42_Syntax_BOT?start=1298152745",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Matcher",
    teamLink: "https://dorahacks.io/buidl/11760",
    teamMVP: "https://t.me/matcher_networking_bot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "SoulMates",
    teamLink: "https://dorahacks.io/buidl/12473",
    teamMVP: "https://t.me/soulmate_dapp_bot/soul_mates",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Tonal",
    teamLink: "https://dorahacks.io/buidl/11948",
    teamMVP: "https://t.me/TonalWinBot/onboarding",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Quyx",
    teamLink: "https://dorahacks.io/buidl/10541",
    teamMVP: "https://t.me/QuyxBot?start",
    teamTrack: "Social Web3",
  },
  {
    teamName: "selllecture",
    teamLink: "https://dorahacks.io/buidl/11241",
    teamMVP: "https://t.me/selllecture_bot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "TONMusic",
    teamLink: "https://dorahacks.io/buidl/11470",
    teamMVP: "https://t.me/ton_music_bot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Money Garden",
    teamLink: "https://dorahacks.io/buidl/11018",
    teamMVP: "https://t.me/moneygardenaibot?start=1365222566",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Shor",
    teamLink: "https://dorahacks.io/buidl/11439",
    teamMVP: "https://t.me/unpacksbot/app",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Tonalty",
    teamLink: "https://dorahacks.io/buidl/12988",
    teamMVP: "https://t.me/ttonalty_bot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Cat Gold Miner",
    teamLink: "https://dorahacks.io/buidl/10853",
    teamMVP: "https://t.me/catgoldminerbot/game",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Tontune",
    teamLink: "https://dorahacks.io/buidl/11413",
    teamMVP: "https://t.me/TontuneBot/Tontune",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Nifty Nerds Network",
    teamLink: "https://dorahacks.io/buidl/11900",
    teamMVP: "https://t.me/niftynerdsnetwork_bot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Gu$$i coin runner",
    teamLink: "https://dorahacks.io/buidl/12952",
    teamMVP: "https://t.me/gussicoin_bot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Mighty",
    teamLink: "https://dorahacks.io/buidl/12479",
    teamMVP: "https://t.me/mightyappbot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "FUN Games",
    teamLink: "https://dorahacks.io/buidl/11928",
    teamMVP: "https://t.me/fungamesrobot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "TravelFrog",
    teamLink: "https://dorahacks.io/buidl/12822",
    teamMVP: "https://t.me/travel_frog_bot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Tonchi",
    teamLink: "https://dorahacks.io/buidl/13228",
    teamMVP: "https://t.me/tonchi_wallet_bot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "GYM on TON",
    teamLink: "https://dorahacks.io/buidl/12861",
    teamMVP: "https://t.me/gymonton_bot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Chick Coop",
    teamLink: "https://dorahacks.io/buidl/11877",
    teamMVP: "https://t.me/chickcoopofficial_bot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Hamston",
    teamLink: "https://dorahacks.io/buidl/12493",
    teamMVP: "https://t.me/Hamstonbot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Bot Gameyard",
    teamLink: "https://dorahacks.io/buidl/12851",
    teamMVP: "https://t.me/Herotonbot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "evenue",
    teamLink: "https://dorahacks.io/buidl/12805",
    teamMVP: "https://t.me/MyEvenueBot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Tonightt",
    teamLink: "https://dorahacks.io/buidl/12951",
    teamMVP: "https://t.me/to_night_bot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Health module for Telegram (tracking steps and fitness)",
    teamLink: "https://dorahacks.io/buidl/12890",
    teamMVP: "mini app inside other telegram client",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Tontch - Boosting Twitch Revenue",
    teamLink: "https://dorahacks.io/buidl/12980",
    teamMVP: "https://t.me/tontch_bot/app",
    teamTrack: "Social Web3",
  },
  {
    teamName: "BuzzTrade - Social Trading for Telegram",
    teamLink: "https://dorahacks.io/buidl/13016",
    teamMVP: "https://t.me/BuzzTradeBot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "PUZZLE SWAP",
    teamLink: "https://dorahacks.io/buidl/13662",
    teamMVP: "https://t.me/puzzle_on_ton_bot/puzzle",
    teamTrack: "DeFi",
  },
  {
    teamName: "FIVA",
    teamLink: "https://dorahacks.io/buidl/13352",
    teamMVP: "https://t.me/fiva_yield_bot",
    teamTrack: "DeFi",
  },
  {
    teamName: "Parroton",
    teamLink: "https://dorahacks.io/buidl/13164",
    teamMVP: "https://t.me/parroton_bot",
    teamTrack: "DeFi",
  },
  {
    teamName: "TON Hedge",
    teamLink: "https://dorahacks.io/buidl/13234",
    teamMVP: "https://t.me/ton_hedge_bot/trade",
    teamTrack: "DeFi",
  },
  {
    teamName: "Prophet",
    teamLink: "https://dorahacks.io/buidl/12847",
    teamMVP: "https://t.me/Prophet_ton_bot",
    teamTrack: "DeFi",
  },
  {
    teamName: "Syntonix",
    teamLink: "https://dorahacks.io/buidl/13535",
    teamMVP: "https://t.me/syntonix_bot",
    teamTrack: "DeFi",
  },
  {
    teamName: "fistack",
    teamLink: "https://dorahacks.io/buidl/13179",
    teamMVP: "https://t.me/hellotma_bot",
    teamTrack: "DeFi",
  },
  {
    teamName: "loot boxes",
    teamLink: "https://dorahacks.io/buidl/11639",
    teamMVP: "https://t.me/loot_box_box_bot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "portfel",
    teamLink: "https://dorahacks.io/buidl/12594",
    teamMVP: "https://t.me/ton_portfel_bot/portfel",
    teamTrack: "DeFi",
  },
  {
    teamName: "Curdle Protocol - Stable Swap on TON blockchain",
    teamLink: "https://dorahacks.io/buidl/13026",
    teamMVP: "https://t.me/dorahack_curdle_bot/curdle_testnet",
    teamTrack: "DeFi",
  },
  {
    teamName: "Polyton",
    teamLink: "https://dorahacks.io/buidl/13248",
    teamMVP: "https://t.me/PolytonMVPBot",
    teamTrack: "DeFi",
  },
  {
    teamName: "Kibble Exchange",
    teamLink: "https://dorahacks.io/buidl/12577",
    teamMVP: "https://t.me/KibbleExchangeBot",
    teamTrack: "DeFi",
  },
  {
    teamName: "TONDropMania",
    teamLink: "https://dorahacks.io/buidl/13176",
    teamMVP: "https://t.me/tondropmania_bot",
    teamTrack: "DeFi",
  },
  {
    teamName: "Wonton.fun",
    teamLink: "https://dorahacks.io/buidl/13205",
    teamMVP: "https://t.me/wontondotfun_bot",
    teamTrack: "DeFi",
  },
  {
    teamName: "drockets",
    teamLink: "https://dorahacks.io/buidl/11661",
    teamMVP: "https://t.me/dRocketsbot",
    teamTrack: "DeFi",
  },
  {
    teamName: "Rainbow Swap ​",
    teamLink: "https://dorahacks.io/buidl/11739",
    teamMVP: "https://t.me/rainbow_swap_bot",
    teamTrack: "DeFi",
  },
  {
    teamName: "Farmix",
    teamLink: "https://dorahacks.io/buidl/11471",
    teamMVP: "https://t.me/FarmixTonbot",
    teamTrack: "DeFi",
  },
  {
    teamName: "Lucky Wallet",
    teamLink: "https://dorahacks.io/buidl/11790",
    teamMVP: "https://t.me/Lucky_wallet_bot/App",
    teamTrack: "DeFi",
  },
  {
    teamName: "Chaser",
    teamLink: "https://dorahacks.io/buidl/11792",
    teamMVP: "https://t.me/ton_chaser_bot/app",
    teamTrack: "DeFi",
  },
  {
    teamName: "Thunder Finance - phase 2",
    teamLink: "https://dorahacks.io/buidl/11623",
    teamMVP:
      "https://t.me/ThunderFinanceTonBot/mainnetV1?startapp=dG9rZW5zOkVRQXhrUWxDUDU1YXhSem0zcG9VMEk2WUhWeXp3eUliRzJJUGl4b2xSZkFLektfcjo3MzMzMTY0NzM1",
    teamTrack: "DeFi",
  },
  {
    teamName: "Krediton TMA Lending Tool",
    teamLink: "https://dorahacks.io/buidl/11203",
    teamMVP: "https://t.me/Kreditonbot/App",
    teamTrack: "DeFi",
  },
  {
    teamName: "The Yield",
    teamLink: "https://dorahacks.io/buidl/11465",
    teamMVP: "https://t.me/the_yield_bot",
    teamTrack: "DeFi",
  },
  {
    teamName: "TONBazaar",
    teamLink: "https://dorahacks.io/buidl/10896",
    teamMVP: "https://t.me/tBzrTestBot/shop",
    teamTrack: "eCommerce",
  },
  {
    teamName: "Autoproof",
    teamLink: "https://dorahacks.io/buidl/13235",
    teamMVP: "https://t.me/autoproofbot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Crypto Magnate",
    teamLink: "https://dorahacks.io/buidl/13263#details",
    teamMVP: "https://t.me/playcryptomagnatebot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Tickyton",
    teamLink: "https://dorahacks.io/buidl/10817",
    teamMVP: "https://t.me/TickyTonBot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "TON Education App",
    teamLink: "https://dorahacks.io/buidl/13218",
    teamMVP: "https://t.me/ton_education_bot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Spruton Telegram Market Manager",
    teamLink: "https://dorahacks.io/buidl/11031",
    teamMVP: "https://t.me/SprutonBot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "BIRD TON",
    teamLink: "https://dorahacks.io/buidl/13497",
    teamMVP: "https://t.me/BIRDTonBot?start=hackaton",
    teamTrack: "eCommerce",
  },
  {
    teamName: "Tea Farm",
    teamLink: "https://dorahacks.io/buidl/13677",
    teamMVP: "https://t.me/TeaFarmTownBot",
    teamTrack: "eCommerce",
  },
  {
    teamName: "FKTON",
    teamLink: "https://dorahacks.io/buidl/12502",
    teamMVP: "https://t.me/FKton_bot/app?startapp=aW52aXRlXzZfNg==",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Boosteam",
    teamLink: "https://dorahacks.io/buidl/12916",
    teamMVP: "https://t.me/boosteambot/app",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Catton",
    teamLink: "https://dorahacks.io/buidl/12834",
    teamMVP: "https://t.me/CattonAiBot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "TonVerify",
    teamLink: "https://dorahacks.io/buidl/13017",
    teamMVP: "https://t.me/verify_ton_bot/verify",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Suzume",
    teamLink: "https://dorahacks.io/buidl/11562",
    teamMVP: "https://t.me/solitaire_szm_bot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Bcoin2048",
    teamLink: "https://dorahacks.io/buidl/11624",
    teamMVP: "https://t.me/Bcoin2048bot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "FOLK",
    teamLink: "https://dorahacks.io/buidl/11694",
    teamMVP: "https://t.me/folklolgame_bot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Meme Battle",
    teamLink: "https://dorahacks.io/buidl/11419",
    teamMVP: "https://t.me/gamememebattle_bot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Bastion Battle",
    teamLink: "https://dorahacks.io/buidl/11087",
    teamMVP: "https://t.me/BastionBattle_bot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Bee Harvest",
    teamLink: "https://dorahacks.io/buidl/12974",
    teamMVP: "https://t.me/beeharvestbot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Miracle",
    teamLink: "https://dorahacks.io/buidl/11743",
    teamMVP: "https://t.me/miracleGameBot/start",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "GLOBULA",
    teamLink: "https://dorahacks.io/buidl/11590",
    teamMVP: "https://t.me/GlobulaSpaceBot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Pixel X Farm",
    teamLink: "https://dorahacks.io/buidl/13047",
    teamMVP: "https://t.me/pixelxfarm_bot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "MELONIA - Innovative Clicker",
    teamLink: "https://dorahacks.io/buidl/13473",
    teamMVP: "https://t.me/meloniaclick_bot/melonia",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "BillyBob",
    teamLink: "https://dorahacks.io/buidl/13289",
    teamMVP: "https://t.me/BillyBobRobot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "TON DURAK",
    teamLink: "https://dorahacks.io/buidl/13425",
    teamMVP: "https://t.me/tondurakgamebot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Gramilla World",
    teamLink: "https://dorahacks.io/buidl/13261",
    teamMVP: "https://t.me/gramilla_beta_bot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Chance​",
    teamLink: "https://dorahacks.io/buidl/13586",
    teamMVP: "https://t.me/chancetg_bot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Ton Heros",
    teamLink: "https://dorahacks.io/buidl/13588",
    teamMVP: "https://t.me/TonHeroesBot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Glory Arena",
    teamLink: "https://dorahacks.io/buidl/11209",
    teamMVP: "https://t.me/GloryArenaBot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Sphynx",
    teamLink: "https://dorahacks.io/buidl/13477",
    teamMVP: "https://t.me/sphynxmeme_bot/bless",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Stargaze (2D Game-fi with NFT Marketplace)",
    teamLink: "https://dorahacks.io/buidl/13403",
    teamMVP: "https://t.me/spaceship_test_bot/Spaceship",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "SettleTON",
    teamLink: "https://dorahacks.io/buidl/11027",
    teamMVP: "https://t.me/settleton_bot",
    teamTrack: "DeFi",
  },
  {
    teamName: "SnapX",
    teamLink: "https://dorahacks.io/buidl/11029",
    teamMVP: "https://t.me/snapx_prod_bot/snapx_app",
    teamTrack: "Social Web3",
  },
  {
    teamName: "PetProject Donation",
    teamLink: "https://dorahacks.io/buidl/12985",
    teamMVP: "https://t.me/pet_project_donations_bot/app",
    teamTrack: "DeFi",
  },
  {
    teamName: "Chessio",
    teamLink: "https://dorahacks.io/buidl/13366",
    teamMVP: "https://t.me/chessiobot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "Planetor",
    teamLink: "https://dorahacks.io/buidl/13301",
    teamMVP: "https://t.me/PlanetorBot",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "SplitApp",
    teamLink: "https://dorahacks.io/buidl/11668",
    teamMVP: "https://t.me/SplitAppTg_bot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Sellz",
    teamLink: "https://dorahacks.io/buidl/11034",
    teamMVP: "https://t.me/sellzbot",
    teamTrack: "eCommerce",
  },
  {
    teamName: "TON Fonates",
    teamLink: "https://dorahacks.io/buidl/11099",
    teamMVP: "https://t.me/fonatesbot",
    teamTrack: "DeFi",
  },
  {
    teamName: "esim4u - experience seamless connectivity",
    teamLink: "https://dorahacks.io/buidl/12497",
    teamMVP: "https://t.me/esim4u_bot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Padzei - Event Recommendations",
    teamLink: "https://dorahacks.io/buidl/12704",
    teamMVP: "https://t.me/padzeibot/app",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Zipsy",
    teamLink: "https://dorahacks.io/buidl/13239",
    teamMVP: "https://t.me/zipsy_bot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "TonPad",
    teamLink: "https://dorahacks.io/buidl/10903",
    teamMVP: "t.me/TonPadXbot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Hamsterdam",
    teamLink: "https://dorahacks.io/buidl/12992",
    teamMVP: "https://t.me/HamsterdamPlayBot/game?startapp=1",
    teamTrack: "Social Web3",
  },
  {
    teamName: "XDAO",
    teamLink: "https://dorahacks.io/buidl/13601",
    teamMVP: "https://t.me/tonxdao_bot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Architec.ton",
    teamLink: "https://dorahacks.io/buidl/11356",
    teamMVP: "https://t.me/ATonDevBot/Wallet",
    teamTrack: "Onboarding systems and games",
  },
  {
    teamName: "OpenLending",
    teamLink: "https://dorahacks.io/buidl/13767",
    teamMVP: "https://t.me/openlend_bot",
    teamTrack: "DeFi",
  },
  {
    teamName: "Snapster | User-friendly DEX-trading Interface",
    teamLink: "https://dorahacks.io/buidl/12995",
    teamMVP: "https://t.me/ton_snapster_bot",
    teamTrack: "DeFi",
  },
  {
    teamName: "Roomzy",
    teamLink: "https://dorahacks.io/buidl/13292",
    teamMVP: "https://t.me/Roooomzy_bot",
    teamTrack: "Social Web3",
  },
  {
    teamName: "WAI AR Farming bot",
    teamLink: "https://dorahacks.io/buidl/11846",
    teamMVP:
      "https://t.me/wai_coin_bot/app?startapp=cac4c524568e0bd8cf4a5d1059c89c79",
    teamTrack: "Social Web3",
  },
  {
    teamName: "Pumpers",
    teamLink: "https://dorahacks.io/buidl/13023",
    teamMVP: "https://t.me/PumpersTGBot/app",
    teamTrack: "DeFi",
  },
];

export const realFinalists = [
  {
    teamName: "Overleap",
    teamLink: "https://dorahacks.io/buidl/13092",
    teamMVP: "https://t.me/overleap_bot",
    teamTrack: "Social Web3",
    place: "Social Web3 nominee",
  },
  {
    teamName: "InOne",
    teamLink: "https://dorahacks.io/buidl/11369",
    teamMVP: "https://t.me/inone_beta_bot",
    teamTrack: "eCommerce",
    place: "eCommerce nominee",
  },
  {
    teamName: "Telegram built-in e-Shop Window",
    teamLink: "https://dorahacks.io/buidl/12854",
    teamMVP: "https://t.me/ShopigramBot",
    teamTrack: "eCommerce",
    place: "eCommerce nominee",
  },
  {
    teamName: "Swipy",
    teamLink: "https://dorahacks.io/buidl/11601",
    teamMVP: "https://t.me/SwipyDatingBot",
    teamTrack: "Social Web3",
    place: "Kucoin winner",
  },
  {
    teamName: "Tonalytics",
    teamLink: "https://dorahacks.io/buidl/11614",
    teamMVP: "https://t.me/tonalytics_bot/app",
    teamTrack: "Social Web3",
    place: "DeFi nominee",
  },
  {
    teamName: "Money Garden",
    teamLink: "https://dorahacks.io/buidl/11018",
    teamMVP: "https://t.me/moneygardenaibot?start=1365222566",
    teamTrack: "GameFI & Onboarding",
    place: "GameFI & Onboarding nominee",
  },
  {
    teamName: "Cat Gold Miner",
    teamLink: "https://dorahacks.io/buidl/10853",
    teamMVP: "https://t.me/catgoldminerbot/game",
    teamTrack: "GameFI & Onboarding",
    place: "GameFI & Onboarding nominee",
  },
  {
    teamName: "TravelFrog",
    teamLink: "https://dorahacks.io/buidl/12822",
    teamMVP: "https://t.me/travel_frog_bot",
    teamTrack: "GameFI & Onboarding",
    place: "GameFI & Onboarding nominee",
  },
  {
    teamName: "Chick Coop",
    teamLink: "https://dorahacks.io/buidl/11877",
    teamMVP: "https://t.me/chickcoopofficial_bot",
    teamTrack: "GameFI & Onboarding",
    place: "GameFI & Onboarding nominee",
  },
  {
    teamName: "Tontch - Boosting Twitch Revenue",
    teamLink: "https://dorahacks.io/buidl/12980",
    teamMVP: "https://t.me/tontch_bot/app",
    teamTrack: "Social Web3",
    place: "Social Web3 nominee",
  },
  {
    teamName: "FIVA",
    teamLink: "https://dorahacks.io/buidl/13352",
    teamMVP: "https://t.me/fiva_yield_bot",
    teamTrack: "DeFi",
    place: "DeFi nominee",
  },
  {
    teamName: "Parroton",
    teamLink: "https://dorahacks.io/buidl/13164",
    teamMVP: "https://t.me/parroton_bot",
    teamTrack: "DeFi",
    place: "DeFi nominee",
  },
  {
    teamName: "TON Hedge",
    teamLink: "https://dorahacks.io/buidl/13234",
    teamMVP: "https://t.me/ton_hedge_bot/trade",
    teamTrack: "DeFi",
    place: "DeFi nominee",
  },
  {
    teamName: "Prophet",
    teamLink: "https://dorahacks.io/buidl/12847",
    teamMVP: "https://t.me/Prophet_ton_bot",
    teamTrack: "DeFi",
    place: "DeFi nominee",
  },
  {
    teamName: "Curdle Protocol - Stable Swap on TON blockchain",
    teamLink: "https://dorahacks.io/buidl/13026",
    teamMVP: "https://t.me/dorahack_curdle_bot/curdle_testnet",
    teamTrack: "DeFi",
    place: "DeFi nominee",
  },
  {
    teamName: "Crypto Magnate",
    teamLink: "https://dorahacks.io/buidl/13263#details",
    teamMVP: "https://t.me/playcryptomagnatebot",
    teamTrack: "GameFI & Onboarding",
    place: "GameFI & Onboarding nominee",
  },
  {
    teamName: "Tea Farm",
    teamLink: "https://dorahacks.io/buidl/13677",
    teamMVP: "https://t.me/TeaFarmTownBot",
    teamTrack: "GameFI & Onboarding",
    place: "GameFI & Onboarding nominee",
  },
  {
    teamName: "Boosteam",
    teamLink: "https://dorahacks.io/buidl/12916",
    teamMVP: "https://t.me/boosteambot/app",
    teamTrack: "Social Web3",
    place: "Social Web3 nominee",
  },
  {
    teamName: "Catton",
    teamLink: "https://dorahacks.io/buidl/12834",
    teamMVP: "https://t.me/CattonAiBot",
    teamTrack: "GameFI & Onboarding",
    place: "Kucoin winner",
  },
  {
    teamName: "SettleTON",
    teamLink: "https://dorahacks.io/buidl/11027",
    teamMVP: "https://t.me/settleton_bot",
    teamTrack: "DeFi",
    place: "DeFi nominee",
  },
  {
    teamName: "Chessio",
    teamLink: "https://dorahacks.io/buidl/13366",
    teamMVP: "https://t.me/chessiobot",
    teamTrack: "GameFI & Onboarding",
    place: "GameFI & Onboarding nominee",
  },
  {
    teamName: "Hamsterdam",
    teamLink: "https://dorahacks.io/buidl/12992",
    teamMVP: "https://t.me/HamsterdamPlayBot/game?startapp=1",
    teamTrack: "GameFI & Onboarding",
    place: "GameFI & Onboarding nominee",
  },
  {
    teamName: "Pumpers",
    teamLink: "https://dorahacks.io/buidl/13023",
    teamMVP: "https://t.me/PumpersTGBot/app",
    teamTrack: "DeFi",
    place: "Kucoin winner",
  },
  {
    teamName: "Rainbow Swap ​",
    teamLink: "https://dorahacks.io/buidl/11739",
    teamMVP: "https://t.me/rainbow_swap_bot",
    teamTrack: "DeFi",
    place: "Kucoin winner",
  },
  {
    teamName: "Shor (Unpacks)",
    teamLink: "https://dorahacks.io/buidl/11439",
    teamMVP: "https://t.me/unpacksbot/app",
    teamTrack: "Social Web3",
    place: "eCommerce nominee",
  },
  {
    teamName: "Portfel",
    teamLink: "https://dorahacks.io/buidl/12594",
    teamMVP: "https://t.me/ton_portfel_bot/portfel",
    teamTrack: "DeFi",
    place: "DeFi nominee",
  },
  {
    teamName: "Chance​",
    teamLink: "https://dorahacks.io/buidl/13586",
    teamMVP: "https://t.me/chancetg_bot",
    teamTrack: "GameFI & Onboarding",
    place: "GameFI & Onboarding nominee",
  },
  {
    teamName: "FaktON",
    teamLink: "https://dorahacks.io/buidl/12502",
    teamMVP: "https://t.me/FKton_bot/app?startapp=aW52aXRlXzZfNg==",
    teamTrack: "GameFI & Onboarding",
    place: "GameFI & Onboarding nominee",
  },
];
